//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_PSD.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int CartId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> MakeupId { get; set; }
        public int Quantity { get; set; }
    
        public virtual User User { get; set; }
        public virtual Makeup Makeup { get; set; }
    }
}
